# Generated by Django 4.1.7 on 2023-03-13 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product_slug'),
    ]

    operations = [
    ]
